---
abstract: 'More functionality for Term::Shell'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Shell-Enhanced
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Accessor::Complex: 0
  Data::Inherited: 0
  Sys::Hostname: 0
  Term::Shell: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Term-Shell-Enhanced
  homepage: http://search.cpan.org/dist/Term-Shell-Enhanced/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/term-shell-enhanced.git
version: 0.05
